<?php

if ( !defined('APP_NAME') ) exit;

//web目录路径
define('APP_WEBDOC_PATH', SYS_BASE_PATH . APP_SEPARATOR_DS . APP_NAME);

!defined('APP_PATH') && define('APP_PATH', APP_WEBDOC_PATH);
define('APP_BASE_PATH', APP_PATH);

//不可对外公开目录路径
define('APP_NOPUBLIC_PATH', APP_BASE_PATH . APP_SEPARATOR_DS . 'nopublic');

//lib根目录
define('APP_NOPUBLIC_LIB_PATH', APP_NOPUBLIC_PATH . APP_SEPARATOR_DS . 'lib');

//conf根目录
define('APP_NOPUBLIC_CONF_PATH', APP_NOPUBLIC_PATH . APP_SEPARATOR_DS . 'conf');

//application根目录
define('APP_NOPUBLIC_APPLICATION_PATH', APP_NOPUBLIC_PATH . APP_SEPARATOR_DS . 'app');

//应用的modules目录
define('APP_NOPUBLIC_MODULES_PATH', APP_NOPUBLIC_APPLICATION_PATH . APP_SEPARATOR_DS . 'modules');

//应用的controllers目录
define('APP_NOPUBLIC_CONTROLLERS_PATH', APP_NOPUBLIC_APPLICATION_PATH . APP_SEPARATOR_DS . 'ctls');

//应用的models目录
define('APP_NOPUBLIC_MODELS_PATH', APP_NOPUBLIC_APPLICATION_PATH . APP_SEPARATOR_DS . 'models');

//应用的logics目录
define('APP_NOPUBLIC_LOGICS_PATH', APP_NOPUBLIC_APPLICATION_PATH . APP_SEPARATOR_DS . 'logics');

//应用的forms目录
define('APP_NOPUBLIC_FORMS_PATH', APP_NOPUBLIC_APPLICATION_PATH . APP_SEPARATOR_DS . 'forms');

//应用的views目录
define('APP_NOPUBLIC_VIEWS_PATH', APP_NOPUBLIC_APPLICATION_PATH . APP_SEPARATOR_DS . 'views');

//应用的模板目录
define('APP_NOPUBLIC_HTML_PATH', APP_NOPUBLIC_VIEWS_PATH . APP_SEPARATOR_DS . 'html');

//应用的模板文件目录
define('APP_NOPUBLIC_TPL_HTML_PATH', APP_NOPUBLIC_VIEWS_PATH . APP_SEPARATOR_DS . 'html');
//应用的模板编译目录
define('APP_NOPUBLIC_TPL_COMPILE_PATH', APP_NOPUBLIC_VIEWS_PATH . APP_SEPARATOR_DS . 'compile');
//应用的模板配置目录
define('APP_NOPUBLIC_TPL_CONFIG_PATH', APP_NOPUBLIC_VIEWS_PATH . APP_SEPARATOR_DS . 'config');
//应用的模板配置目录
define('APP_NOPUBLIC_TPL_CACHE_PATH', APP_NOPUBLIC_VIEWS_PATH . APP_SEPARATOR_DS . 'cache');

//应用的模板文件扩展名的配置索引key
define('APP_NOPUBLIC_TPL_EXT_KEY', SYS_NOPUBLIC_TPL_EXT_KEY);
//应用的模板文件扩展名
define('APP_NOPUBLIC_TPL_EXT_VALUE', SYS_NOPUBLIC_TPL_EXT_VALUE);

//应用的helper目录
define('APP_NOPUBLIC_HELPER_PATH', APP_NOPUBLIC_VIEWS_PATH . APP_SEPARATOR_DS . 'helper');
define('APP_NOPUBLIC_HELPER_PREFIX', 'My_View_Helper');

//应用的cache目录
define('APP_NOPUBLIC_CACHE_PATH', APP_NOPUBLIC_APPLICATION_PATH . APP_SEPARATOR_DS . 'Cache');

//应用的layouts目录
define('APP_NOPUBLIC_LAYOUTS_PATH', APP_NOPUBLIC_APPLICATION_PATH . APP_SEPARATOR_DS . 'layouts');

//语言翻译目录
define('APP_NOPUBLIC_TRANSLATE_PATH', APP_NOPUBLIC_APPLICATION_PATH . APP_SEPARATOR_DS . 'languages');

//form提示信息翻译目录
define('APP_NOPUBLIC_TRANSLATE_FORM_FILE', APP_NOPUBLIC_TRANSLATE_PATH . APP_SEPARATOR_DS . 'simpleChinese.php');

?>